/* Auto-generated by scripts/gen_tz.py. Do not edit by hand. */
#ifndef TZ_CITIES_H
#define TZ_CITIES_H

#include <stdint.h>

typedef struct {
    const char *name;     /* friendly label, e.g. "Singapore" */
    const char *zone;     /* IANA zone, e.g. "Asia/Singapore" */
    const char *posix_tz; /* POSIX TZ string, e.g. "<+08>-8" */
} tz_city_t;

typedef struct {
    const char *name;     /* continent label */
    uint16_t    first;    /* first index into k_tz_cities (inclusive) */
    uint16_t    last;     /* last index (exclusive) */
} tz_continent_t;

#define TZ_CITY_COUNT 126
#define TZ_CONTINENT_COUNT 6
#define TZ_DEFAULT_CITY_INDEX 44  /* Singapore */

static const tz_city_t k_tz_cities[TZ_CITY_COUNT] = {
    { "Cairo"               , "Africa/Cairo"                      , "EET-2EEST,M4.5.5/0,M10.5.4/24" },  /* 0 */
    { "Lagos"               , "Africa/Lagos"                      , "WAT-1" },  /* 1 */
    { "Johannesburg"        , "Africa/Johannesburg"               , "SAST-2" },  /* 2 */
    { "Nairobi"             , "Africa/Nairobi"                    , "EAT-3" },  /* 3 */
    { "Casablanca"          , "Africa/Casablanca"                 , "XXX-2<+01>-1,0/0,J365/23" },  /* 4 */
    { "Algiers"             , "Africa/Algiers"                    , "CET-1" },  /* 5 */
    { "Addis Ababa"         , "Africa/Addis_Ababa"                , "EAT-3" },  /* 6 */
    { "Accra"               , "Africa/Accra"                      , "GMT0" },  /* 7 */
    { "Khartoum"            , "Africa/Khartoum"                   , "CAT-2" },  /* 8 */
    { "Dakar"               , "Africa/Dakar"                      , "GMT0" },  /* 9 */
    { "Tunis"               , "Africa/Tunis"                      , "CET-1" },  /* 10 */
    { "Kinshasa"            , "Africa/Kinshasa"                   , "WAT-1" },  /* 11 */
    { "New York"            , "America/New_York"                  , "EST5EDT,M3.2.0,M11.1.0" },  /* 12 */
    { "Chicago"             , "America/Chicago"                   , "CST6CDT,M3.2.0,M11.1.0" },  /* 13 */
    { "Denver"              , "America/Denver"                    , "MST7MDT,M3.2.0,M11.1.0" },  /* 14 */
    { "Phoenix"             , "America/Phoenix"                   , "MST7" },  /* 15 */
    { "Los Angeles"         , "America/Los_Angeles"               , "PST8PDT,M3.2.0,M11.1.0" },  /* 16 */
    { "Anchorage"           , "America/Anchorage"                 , "AKST9AKDT,M3.2.0,M11.1.0" },  /* 17 */
    { "Honolulu"            , "Pacific/Honolulu"                  , "HST10" },  /* 18 */
    { "Toronto"             , "America/Toronto"                   , "EST5EDT,M3.2.0,M11.1.0" },  /* 19 */
    { "Vancouver"           , "America/Vancouver"                 , "PST8PDT,M3.2.0,M11.1.0" },  /* 20 */
    { "St Johns"            , "America/St_Johns"                  , "NST3:30NDT,M3.2.0,M11.1.0" },  /* 21 */
    { "Halifax"             , "America/Halifax"                   , "AST4ADT,M3.2.0,M11.1.0" },  /* 22 */
    { "Mexico City"         , "America/Mexico_City"               , "CST6" },  /* 23 */
    { "Guatemala"           , "America/Guatemala"                 , "CST6" },  /* 24 */
    { "Panama"              , "America/Panama"                    , "EST5" },  /* 25 */
    { "Havana"              , "America/Havana"                    , "CST5CDT,M3.2.0/0,M11.1.0/1" },  /* 26 */
    { "Bogota"              , "America/Bogota"                    , "<-05>5" },  /* 27 */
    { "Lima"                , "America/Lima"                      , "<-05>5" },  /* 28 */
    { "Caracas"             , "America/Caracas"                   , "<-04>4" },  /* 29 */
    { "Santiago"            , "America/Santiago"                  , "<-04>4<-03>,M9.1.6/24,M4.1.6/24" },  /* 30 */
    { "Buenos Aires"        , "America/Argentina/Buenos_Aires"    , "<-03>3" },  /* 31 */
    { "Sao Paulo"           , "America/Sao_Paulo"                 , "<-03>3" },  /* 32 */
    { "Manaus"              , "America/Manaus"                    , "<-04>4" },  /* 33 */
    { "Montevideo"          , "America/Montevideo"                , "<-03>3" },  /* 34 */
    { "La Paz"              , "America/La_Paz"                    , "<-04>4" },  /* 35 */
    { "Asuncion"            , "America/Asuncion"                  , "<-03>3" },  /* 36 */
    { "San Juan PR"         , "America/Puerto_Rico"               , "AST4" },  /* 37 */
    { "Tokyo"               , "Asia/Tokyo"                        , "JST-9" },  /* 38 */
    { "Seoul"               , "Asia/Seoul"                        , "KST-9" },  /* 39 */
    { "Pyongyang"           , "Asia/Pyongyang"                    , "KST-9" },  /* 40 */
    { "Beijing"             , "Asia/Shanghai"                     , "CST-8" },  /* 41 */
    { "Hong Kong"           , "Asia/Hong_Kong"                    , "HKT-8" },  /* 42 */
    { "Taipei"              , "Asia/Taipei"                       , "CST-8" },  /* 43 */
    { "Singapore"           , "Asia/Singapore"                    , "<+08>-8" },  /* 44 */
    { "Kuala Lumpur"        , "Asia/Kuala_Lumpur"                 , "<+08>-8" },  /* 45 */
    { "Jakarta"             , "Asia/Jakarta"                      , "WIB-7" },  /* 46 */
    { "Bangkok"             , "Asia/Bangkok"                      , "<+07>-7" },  /* 47 */
    { "Hanoi"               , "Asia/Ho_Chi_Minh"                  , "<+07>-7" },  /* 48 */
    { "Manila"              , "Asia/Manila"                       , "PST-8" },  /* 49 */
    { "Yangon"              , "Asia/Yangon"                       , "<+0630>-6:30" },  /* 50 */
    { "Dhaka"               , "Asia/Dhaka"                        , "<+06>-6" },  /* 51 */
    { "Kolkata"             , "Asia/Kolkata"                      , "IST-5:30" },  /* 52 */
    { "Mumbai"              , "Asia/Kolkata"                      , "IST-5:30" },  /* 53 */
    { "Colombo"             , "Asia/Colombo"                      , "<+0530>-5:30" },  /* 54 */
    { "Kathmandu"           , "Asia/Kathmandu"                    , "<+0545>-5:45" },  /* 55 */
    { "Karachi"             , "Asia/Karachi"                      , "PKT-5" },  /* 56 */
    { "Tashkent"            , "Asia/Tashkent"                     , "<+05>-5" },  /* 57 */
    { "Almaty"              , "Asia/Almaty"                       , "<+05>-5" },  /* 58 */
    { "Tehran"              , "Asia/Tehran"                       , "<+0330>-3:30" },  /* 59 */
    { "Baghdad"             , "Asia/Baghdad"                      , "<+03>-3" },  /* 60 */
    { "Riyadh"              , "Asia/Riyadh"                       , "<+03>-3" },  /* 61 */
    { "Dubai"               , "Asia/Dubai"                        , "<+04>-4" },  /* 62 */
    { "Jerusalem"           , "Asia/Jerusalem"                    , "IST-2IDT,M3.4.4/26,M10.5.0" },  /* 63 */
    { "Beirut"              , "Asia/Beirut"                       , "EET-2EEST,M3.5.0/0,M10.5.0/0" },  /* 64 */
    { "Yerevan"             , "Asia/Yerevan"                      , "<+04>-4" },  /* 65 */
    { "Tbilisi"             , "Asia/Tbilisi"                      , "<+04>-4" },  /* 66 */
    { "Yekaterinburg"       , "Asia/Yekaterinburg"                , "<+05>-5" },  /* 67 */
    { "Novosibirsk"         , "Asia/Novosibirsk"                  , "<+07>-7" },  /* 68 */
    { "Krasnoyarsk"         , "Asia/Krasnoyarsk"                  , "<+07>-7" },  /* 69 */
    { "Irkutsk"             , "Asia/Irkutsk"                      , "<+08>-8" },  /* 70 */
    { "Yakutsk"             , "Asia/Yakutsk"                      , "<+09>-9" },  /* 71 */
    { "Vladivostok"         , "Asia/Vladivostok"                  , "<+10>-10" },  /* 72 */
    { "Magadan"             , "Asia/Magadan"                      , "<+11>-11" },  /* 73 */
    { "Kamchatka"           , "Asia/Kamchatka"                    , "<+12>-12" },  /* 74 */
    { "London"              , "Europe/London"                     , "GMT0BST,M3.5.0/1,M10.5.0" },  /* 75 */
    { "Dublin"              , "Europe/Dublin"                     , "GMT0IST,M3.5.0/1,M10.5.0" },  /* 76 */
    { "Lisbon"              , "Europe/Lisbon"                     , "WET0WEST,M3.5.0/1,M10.5.0" },  /* 77 */
    { "Reykjavik"           , "Atlantic/Reykjavik"                , "GMT0" },  /* 78 */
    { "Paris"               , "Europe/Paris"                      , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 79 */
    { "Madrid"              , "Europe/Madrid"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 80 */
    { "Berlin"              , "Europe/Berlin"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 81 */
    { "Amsterdam"           , "Europe/Amsterdam"                  , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 82 */
    { "Brussels"            , "Europe/Brussels"                   , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 83 */
    { "Zurich"              , "Europe/Zurich"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 84 */
    { "Rome"                , "Europe/Rome"                       , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 85 */
    { "Vienna"              , "Europe/Vienna"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 86 */
    { "Prague"              , "Europe/Prague"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 87 */
    { "Warsaw"              , "Europe/Warsaw"                     , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 88 */
    { "Stockholm"           , "Europe/Stockholm"                  , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 89 */
    { "Oslo"                , "Europe/Oslo"                       , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 90 */
    { "Copenhagen"          , "Europe/Copenhagen"                 , "CET-1CEST,M3.5.0,M10.5.0/3" },  /* 91 */
    { "Helsinki"            , "Europe/Helsinki"                   , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 92 */
    { "Athens"              , "Europe/Athens"                     , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 93 */
    { "Bucharest"           , "Europe/Bucharest"                  , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 94 */
    { "Sofia"               , "Europe/Sofia"                      , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 95 */
    { "Istanbul"            , "Europe/Istanbul"                   , "<+03>-3" },  /* 96 */
    { "Moscow"              , "Europe/Moscow"                     , "MSK-3" },  /* 97 */
    { "Kyiv"                , "Europe/Kyiv"                       , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 98 */
    { "Minsk"               , "Europe/Minsk"                      , "<+03>-3" },  /* 99 */
    { "Riga"                , "Europe/Riga"                       , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 100 */
    { "Tallinn"             , "Europe/Tallinn"                    , "EET-2EEST,M3.5.0/3,M10.5.0/4" },  /* 101 */
    { "Sydney"              , "Australia/Sydney"                  , "AEST-10AEDT,M10.1.0,M4.1.0/3" },  /* 102 */
    { "Melbourne"           , "Australia/Melbourne"               , "AEST-10AEDT,M10.1.0,M4.1.0/3" },  /* 103 */
    { "Brisbane"            , "Australia/Brisbane"                , "AEST-10" },  /* 104 */
    { "Perth"               , "Australia/Perth"                   , "AWST-8" },  /* 105 */
    { "Adelaide"            , "Australia/Adelaide"                , "ACST-9:30ACDT,M10.1.0,M4.1.0/3" },  /* 106 */
    { "Darwin"              , "Australia/Darwin"                  , "ACST-9:30" },  /* 107 */
    { "Hobart"              , "Australia/Hobart"                  , "AEST-10AEDT,M10.1.0,M4.1.0/3" },  /* 108 */
    { "Auckland"            , "Pacific/Auckland"                  , "NZST-12NZDT,M9.5.0,M4.1.0/3" },  /* 109 */
    { "Wellington"          , "Pacific/Auckland"                  , "NZST-12NZDT,M9.5.0,M4.1.0/3" },  /* 110 */
    { "Chatham"             , "Pacific/Chatham"                   , "<+1245>-12:45<+1345>,M9.5.0/2:45,M4.1.0/3:45" },  /* 111 */
    { "Fiji"                , "Pacific/Fiji"                      , "<+12>-12" },  /* 112 */
    { "Port Moresby"        , "Pacific/Port_Moresby"              , "<+10>-10" },  /* 113 */
    { "Noumea"              , "Pacific/Noumea"                    , "<+11>-11" },  /* 114 */
    { "Apia"                , "Pacific/Apia"                      , "<+13>-13" },  /* 115 */
    { "Tahiti"              , "Pacific/Tahiti"                    , "<-10>10" },  /* 116 */
    { "Guam"                , "Pacific/Guam"                      , "ChST-10" },  /* 117 */
    { "Midway"              , "Pacific/Midway"                    , "SST11" },  /* 118 */
    { "McMurdo"             , "Antarctica/McMurdo"                , "NZST-12NZDT,M9.5.0,M4.1.0/3" },  /* 119 */
    { "Casey"               , "Antarctica/Casey"                  , "<+08>-8" },  /* 120 */
    { "Davis"               , "Antarctica/Davis"                  , "<+07>-7" },  /* 121 */
    { "Vostok"              , "Antarctica/Vostok"                 , "<+05>-5" },  /* 122 */
    { "Rothera"             , "Antarctica/Rothera"                , "<-03>3" },  /* 123 */
    { "Palmer"              , "Antarctica/Palmer"                 , "<-03>3" },  /* 124 */
    { "Troll"               , "Antarctica/Troll"                  , "<+00>0<+02>-2,M3.5.0/1,M10.5.0/3" },  /* 125 */
};

static const tz_continent_t k_tz_continents[TZ_CONTINENT_COUNT] = {
    { "Africa"      , 0, 12 },
    { "Americas"    , 12, 38 },
    { "Asia"        , 38, 75 },
    { "Europe"      , 75, 102 },
    { "Oceania"     , 102, 119 },
    { "Antarctica"  , 119, 126 },
};

#endif /* TZ_CITIES_H */
