#!/usr/bin/env python3
"""Emit main/i18n_strings.h plus a CJK glyph-subset font from the
translations table.

Outputs:
  main/i18n_strings.h     -- C arrays of UTF-8 strings (one per language)
                             plus an enum of keys.
  main/font_cjk_14.c      -- LVGL font binary covering every code point used
                             across all locales at 14 px (matches our menu
                             body font size).

Run from repo root:
    python3 scripts/gen_i18n.py
"""

import os, sys, subprocess, tempfile, pathlib
from translations import LANGS, TRANSLATIONS

REPO   = pathlib.Path(__file__).resolve().parent.parent
OUT_H  = REPO / "main" / "i18n_strings.h"
OUT_C  = REPO / "main" / "font_cjk_14.c"
SRC_FONT_CJK = os.path.expanduser("~/Library/Fonts/NotoSansCJK.ttc")

def keys():
    return [r[0] for r in TRANSLATIONS]

def text_for(lang_idx):
    # column 1+lang_idx in TRANSLATIONS rows
    return [r[1 + lang_idx] for r in TRANSLATIONS]

def c_str(s):
    out = []
    for ch in s.encode("utf-8"):
        if ch == ord('"'):  out.append('\\"')
        elif ch == ord('\\'): out.append('\\\\')
        elif ch == ord('\n'): out.append('\\n')
        elif 0x20 <= ch < 0x7f: out.append(chr(ch))
        else: out.append('\\x%02x' % ch)
    return '"' + ''.join(out) + '"'

def collect_codepoints():
    """Every distinct code point used in any non-en string. We exclude
    pure ASCII because we already have lv_font_montserrat_* covering it."""
    cps = set()
    for row in TRANSLATIONS:
        for s in row[2:]:  # zh, ja, ko
            for c in s:
                if ord(c) > 0x7f:
                    cps.add(ord(c))
    return sorted(cps)

def emit_strings_header():
    lines = []
    lines.append("/* Auto-generated by scripts/gen_i18n.py. Do not edit by hand. */")
    lines.append("#ifndef I18N_STRINGS_H")
    lines.append("#define I18N_STRINGS_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("typedef enum {")
    for i, k in enumerate(keys()):
        lines.append(f"    I18N_{k.upper()} = {i},")
    lines.append(f"    I18N_KEY_COUNT")
    lines.append("} i18n_key_t;")
    lines.append("")
    lines.append(f"#define I18N_LANG_COUNT {len(LANGS)}")
    lines.append("")
    lines.append("/* Names of the languages, in their own script. Used by the picker. */")
    lines.append("static const char *const k_i18n_lang_names[I18N_LANG_COUNT] = {")
    for code, native in LANGS:
        lines.append(f"    {c_str(native)},  /* {code} */")
    lines.append("};")
    lines.append("")
    lines.append("/* All translated strings, indexed [lang][key]. Stored as UTF-8. */")
    lines.append("static const char *const k_i18n_strings[I18N_LANG_COUNT][I18N_KEY_COUNT] = {")
    for li, (code, _native) in enumerate(LANGS):
        lines.append(f"    /* {code} */ {{")
        col = li + 1  # 0=key, 1+=langs in TRANSLATIONS row
        for row in TRANSLATIONS:
            k = row[0]
            v = row[col] if col < len(row) else row[1]  # fall back to en if missing
            lines.append(f"        [I18N_{k.upper()}] = {c_str(v)},")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* I18N_STRINGS_H */")
    OUT_H.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT_H}: {len(keys())} keys x {len(LANGS)} languages",
          file=sys.stderr)

def emit_font(cps):
    if not cps:
        print("no non-ASCII code points -- skipping font generation", file=sys.stderr)
        return
    # lv_font_conv accepts -r 0xHHHH ranges. Group runs to keep CLI shorter.
    ranges = []
    start = prev = cps[0]
    for cp in cps[1:]:
        if cp == prev + 1:
            prev = cp; continue
        ranges.append((start, prev))
        start = prev = cp
    ranges.append((start, prev))
    # We *don't* subset to just the cps used by the translations -- we
    # want broad CJK coverage so dynamic / future text (typed input,
    # ICY metadata, station names) renders too. The fixed ranges below
    # cover GBK, Hangul Syllables, and Japanese kana + punctuation.
    fixed_ranges = [
        (0x0020, 0x007E),  # Basic Latin
        (0x00A0, 0x00FF),  # Latin-1 supplement
        (0x2010, 0x2027),  # General punctuation
        (0x3000, 0x303F),  # CJK punctuation
        (0x3040, 0x309F),  # Hiragana
        (0x30A0, 0x30FF),  # Katakana
        (0x4E00, 0x9FFF),  # CJK unified ideographs (covers GBK + JP kanji)
        (0xAC00, 0xD7A3),  # Hangul syllables
        (0xFF00, 0xFFEF),  # Halfwidth/fullwidth forms
    ]
    range_args = []
    for a, b in fixed_ranges:
        range_args += ["-r", f"0x{a:04X}-0x{b:04X}"]

    # NotoSansCJK.ttc covers all of CJK + Hangul. Extract a single face
    # (Regular) once and cache so re-runs are fast.
    ttf = REPO / "scripts" / ".cache" / "NotoSansCJK_Regular.ttf"
    ttf.parent.mkdir(exist_ok=True)
    if not ttf.exists():
        from fontTools import ttLib
        col = ttLib.TTCollection(SRC_FONT_CJK)
        # Pick the face whose name ends in "Regular"; falls back to face 0.
        idx = 0
        for i, f in enumerate(col):
            full = f["name"].getDebugName(4) or ""
            if "Regular" in full or "regular" in full:
                idx = i; break
        col.fonts[idx].save(str(ttf))
        print(f"extracted {ttf} (face {idx})", file=sys.stderr)

    cmd = [
        "lv_font_conv",
        "--no-compress",
        "--bpp", "1",
        "--size", "14",
        "--font", str(ttf),
    ] + range_args + [
        "--format", "lvgl",
        "-o", str(OUT_C),
    ]
    print("running:", " ".join(cmd[:7] + ["...range..."] + [cmd[-3], cmd[-2], cmd[-1]]),
          file=sys.stderr)
    subprocess.check_call(cmd)
    print(f"wrote {OUT_C}: {len(cps)} glyphs", file=sys.stderr)

def main():
    cps = collect_codepoints()
    emit_strings_header()
    emit_font(cps)
    return 0

if __name__ == "__main__":
    sys.exit(main())
